In [1]:
import torch
from torchrl.data import Bounded, Unbounded, Composite, Categorical


In [ ]:
array = [1,2,3]
array

1

In [5]:
[i for i in [1]][0]

1

In [7]:
x = torch.tensor([1.0,2.0,3.0,4.0,5.0,6.0])
x

tensor([1., 2., 3., 4., 5., 6.])

In [6]:
x[1:5]

tensor([2., 3., 4., 5.])

In [8]:
x[5:]

tensor([6.])

In [12]:
torch.Size().numel()

1

In [17]:
torch.ones((3,2)).numel()

6

In [2]:
action_spec = Bounded(low=-1, high=1, shape=(), dtype=torch.float32)

In [6]:
action_spec.shape.numel()

1